apiVersion: v1
kind: ServiceAccount
metadata:
  name: wam
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wam
rules:
  # this could probably be more limited
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - pods/status
      - pods/binding
      - deployments/scale
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wam
subjects:
  - kind: ServiceAccount
    name: wam
    namespace: default
