apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wam-scheduler.fullname" . }}
  labels:
    {{- include "wam-scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "wam-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wam-scheduler.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wam-scheduler.fullname" . }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/kube-scheduler
            - --leader-elect=false
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v
            - "5"
          env:
            - name: WAM_REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: WAM_REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: WAM_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wam-scheduler.fullname" . }}
                  key: WAM_REDIS_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          volumeMounts:
            - mountPath: /etc/kubernetes/scheduler-config.yaml
              name: config
              subPath: scheduler-config.yaml
      volumes:
        - configMap:
            name: {{ include "wam-scheduler.fullname" . }}-config
          name: config
