apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wam-scheduler.fullname" . }}-config
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: wam-scheduler
        plugins:
          preFilter:
            enabled:
              - name: WAM
          filter:
            enabled:
              - name: WAM
            disabled:
              - name: "*"
          postBind:
            enabled:
              - name: WAM
        pluginConfig:
          - name: WAM
            args:
              test: "test"
