apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wam-scheduler.fullname" . }}
type: Opaque
stringData:
  WAM_REDIS_PASSWORD: "{{ .Values.redis.password }}"
  WAM_POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
