apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wam-scheduler.fullname" . }}
  labels:
    {{- include "wam-scheduler.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wam-scheduler.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - pods/binding
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csinodes
      - csidrivers
      - csistoragecapacities
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - services
      - namespaces
      - configmaps
      - replicationcontrollers
      - persistentvolumes
      - poddisruptionbudgets
      - replicasets
      - statefulsets
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wam-scheduler.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wam-scheduler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wam-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
