apiVersion: v1
kind: Service
metadata:
  name: {{ include "wam.fullname" . }}
  labels:
    {{- include "wam.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.listenPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wam.selectorLabels" . | nindent 4 }}
