apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wam.fullname" . }}
  labels:
    {{- include "wam.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wam.fullname" . }}
rules:
  # this could probably be more limited
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - pods/status
      - pods/binding
      - deployments/scale
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wam.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wam.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wam.fullname" . }}
    namespace: {{ .Release.Namespace }}
