apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-b.fullname" . }}
  labels:
    {{- include "test-b.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "test-b.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-b.labels" . | nindent 8 }}
    spec:
      schedulerName: wam-scheduler
      containers:
        - name: test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
