replicas: 1

image:
  repository: ghcr.io/vidbregar/workload-actions-manager/wam-scheduler
  pullPolicy: Always
  tag: "0.1.0"

nameOverride: ""
fullnameOverride: ""

redis:
  host: "wam-redis-master.wam.svc.cluster.local"
  port: "6379"
  password: "redis_test_password"
