replicas: 1

image:
  repository: k3d-registry.localhost:50000/wam-scheduler
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

redis:
  host: "wam-redis-master.default.svc.cluster.local"
  port: "6379"
  password: "redis_test_password"
