---
name: Lint & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --all --debug --chart-dirs=deploy --validate-maintainers=false

  go-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - wam
        # - wam-scheduler # todo: linting makes sense only for the code that was added on top of scheduler-plugins

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          working-directory: ${{ matrix.folder }}
